### ISSUE TITLE
Wrap super calls in conditionals

### ISSUE THREAD

**Issue by ssutar** [ember-codemods/ember-es6-class-codemod#30]
The `super.method` throws an error if the `method` is not present in the parent class. Unlike `this._super` which fails silently.

We can wrap the calls like:
```
if (super.method) {
  super.method();
}
```

**Comment by pzuraq** [comment]
I'm concerned about what would happen when `super` is used inline in the code:

```js
validate(options) {
  return this._super(options) && customValidation(options);
}
```

This would have to become something like:

```js
validate(options) {
  return (super.validate && super.validate(options)) && customValidations(options);
}
```

Basically, we can't safely replace an Expression with a Statement. We could add the Statement at the beginning and refer to it throughout:

```js
validate(options) {
  let superValue = super.validate && super.validate(options);

  return superValue && customValidations(options);
}
```

but I don't think that's necessarily cleaner. What do you think @scalvert @rwjblue ?

**Comment by ssutar** [comment]
I think we can target only expression statements and let the users handle the inline instances. As it would be difficult to correctly figure out the order via codemods.

But more frequent instance like `this._super(...arguments);` should be handled by codemods.

So something like 
```
this._super(...arguments);
```
would be wrapped
```
if (super.method) {
  super.method(...arguments);
}
```
But something like this
```
this._super(options) && customValidation(options);
```
would be transformed (but not wrapped) to 
```
super.validate(options) && customValidations(options)
```
It would error out in case `validate` isn't present in the super class

**Comment by pzuraq** [comment]
I think it'd be better to be consistent here, rather than branch if different cases. We should focus on just the case where we do have telemetry data and know whether or not `super` exists, because that's the happy path that we want users to be on, so it should be the most polished.

We can always revisit this case in the future, but for now I think we should assume the data will exist, and throw if it does not.

**Comment by ssutar** [comment]
I don't fully agree with it. I think codemods should handle the most common case.

But I do agree that this is something we can revisit later. And assume for now that the runtime data is available.
