### ISSUE TITLE
Pod structure error

### ISSUE THREAD

**Issue by artemgurzhii** [ember-codemods/ember-es6-class-codemod#79]
I guess `ember-es6-class-codemod` is trying to name classes corresponding to their file names.

I'm using pods and I'm having following structure
 - **app/pods/authenticated**
   - **controller.js**
   - **route.js**
   - **template.hbs**

File `route.js` was transformed into this

**Result:**
```js
import Route from '@ember/routing/route';

export default class Route extends Route {
  // ...
}
```
So I received error `Route is already defined`

**Expected:**
```js
import Route from '@ember/routing/route';

export default class AuthenticatedRoute extends Route {
  // ...
}
```

**Comment by pzuraq** [comment]
This is related to #52 as well, we need to get the test suite to a place where we can merge that PR

**Comment by artemgurzhii** [comment]
@pzuraq Thanks and sorry for disturbing.
